title: Roll Over Red
email: fourblumutts@gmail.com
description: >-
  Uniting Americans behind better leaders.

# Correct URL Settings
url: "http://rolloverred.com"
baseurl: "" 

instagram_username: roll.over.red

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Change 'gallery' to 'products' here
collections:
  products:
    output: true
    permalink: /products/:path/